// <auto-generated />
namespace OurHome.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class WTF_Add_ResourceType_And_Make_Id_Int : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(WTF_Add_ResourceType_And_Make_Id_Int));
        
        string IMigrationMetadata.Id
        {
            get { return "201704110715136_WTF_Add_ResourceType_And_Make_Id_Int"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
