// <auto-generated />
namespace OurHome.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class WTF_Remove_ResourceType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(WTF_Remove_ResourceType));
        
        string IMigrationMetadata.Id
        {
            get { return "201704110714311_WTF_Remove_ResourceType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
